#!/bin/bash

echo "🎰 Casino Program - Quick Reference"
echo "===================================="
echo ""
echo "Program ID: 7Ld5S7rV2vpUWF8YYmfoe2eeXjR2wuEEY534QEFstt3F"
echo "Network: Devnet"
echo "Authority: A24myXDMBj4FPMWuzBYsEyhxMtZgfoUmHiEF3pFBfecK"
echo ""
echo "📊 Program Status:"
solana program show 7Ld5S7rV2vpUWF8YYmfoe2eeXjR2wuEEY534QEFstt3F
echo ""
echo "🔗 Explorer Links:"
echo "- Solana Explorer: https://explorer.solana.com/address/7Ld5S7rV2vpUWF8YYmfoe2eeXjR2wuEEY534QEFstt3F?cluster=devnet"
echo "- Solscan: https://solscan.io/account/7Ld5S7rV2vpUWF8YYmfoe2eeXjR2wuEEY534QEFstt3F?cluster=devnet"
echo ""
echo "📖 Next Steps:"
echo "1. Start dev server: npm run dev"
echo "2. Connect with admin wallet in browser"
echo "3. Open browser console and run:"
echo ""
echo "   import { CasinoAdmin } from './src/utils/admin';"
echo "   const admin = new CasinoAdmin(connection, wallet);"
echo "   await admin.setupCasino(10); // Initialize + fund"
echo ""
echo "✨ See INTEGRATION_COMPLETE.md for full guide"
